spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
#    url: jdbc:mysql://localhost:3306/test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
